### PR TITLE
fix(FindFLANN): set(FLANN_FOUND ON) if target already defined

### LINKED ISSUE #37: CMake Error finding lib FLANN when using PCL in a project (ROS Jazzy)
```
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:64 (message):
  search is required but flann was not found
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:396 (pcl_report_not_found)
  /usr/lib/x86_64-linux-gnu/cmake/pcl/PCLConfig.cmake:588 (find_external_library)
  /opt/ros/jazzy/share/pcl_conversions/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /opt/ros/jazzy/share/pcl_conversions/cmake/pcl_conversionsConfig.cmake:41 (include)
  /opt/ros/jazzy/share/pcl_ros/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /opt/ros/jazzy/share/pcl_ros/cmake/pcl_rosConfig.cmake:41 (include)
  /home/rein/dev/autoware/install/share/autoware_point_types/cmake/ament_cmake_export_dependencies-extras.cmake:21 (find_package)
  /home/rein/dev/autoware/install/share/autoware_point_types/cmake/autoware_point_typesConfig.cmake:41 (include)
  /opt/ros/jazzy/share/ament_cmake_auto/cmake/ament_auto_find_build_dependencies.cmake:67 (find_package)
  /opt/ros/jazzy/share/autoware_cmake/cmake/autoware_package.cmake:49 (ament_auto_find_build_dependencies)
  CMakeLists.txt:5 (autoware_package)
```

### PR DESCRIPTION
**Pull request by reinzor**
Fixes #37

Based on https://github.com/PointCloudLibrary/pcl/blob/master/cmake/Modules/FindFLANN.cmake

### CODE REVIEW

**Comment by Timple** [comment]
For users wanting to try this solution. It will still fail if you have the `apt` version installed, so remove that first before compiling this from source.

**Review by poggenhans — APPROVED** [review]
LGTM. Can you merge please @keroe

**Comment by reinzor** [comment]
Would be great if we can have a release bump afterwards :). This will fix the build on `ros 2` `Jazzy`.

**Comment by Timple** [comment]
Subtle ping...
The whole autoware codebase cannot be installed on jazzy because of this package breaking `FindFLANN`.

Even if compiled from source, the apt version (if installed) still breaks it :slightly_frowning_face:

**Comment by Timple** [comment]
Weekly ping. This is breaking other packages at the moment...

Pinging @keroe as you did the last release for this package.

**Comment by Timple** [comment]
Thank you!

I notice there is a new release `1.0.11` but I'm missing a rosdep PR for this for rolling and jazzy.
Could this package be bloomed? :pray:

**Comment by poggenhans** [comment]
Here it is (among others): https://github.com/ros/rosdistro/pull/42915

**Comment by Timple** [comment]
Great, thank you!

**Comment by reinzor** [comment]
We just missed the sync, but next time it will be in, thanks 😀

**Pull request merged**
